In [157]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None
df_ft = pd.read_csv('data/financial.csv', sep=';')
df_t=pd.read_csv('data/times.csv', sep=';')
df_mo=pd.read_csv('data/mail.csv', sep=';')
df_cnbc=pd.read_csv('data/cnbc.csv', sep=';')
df_forbes=pd.read_csv('data/forbes.csv', sep=';')
df_bloomberg=pd.read_csv('data/bloom.csv', sep=';')

-----------------------------------------------------------------------------------------------------------------------

GENERAL FUNCTIONS 

-----------------------------------------------------------------------------------------------------------------------

In [155]:
def substring_date(a):  #for mail online to substract only date of the whole string
   return a[a.find('\n')+2:a.find(',')]
   #return a[a.find('\n\n ')+2:a.find(',')]

def month_converter(date):
       d =date.split()
    
       months = {'jan': '01','feb': '02','mar': '03','apr':'04','may':'05','jun':'06','jul':'07','aug':'08','sep':'09','oct':'10','nov':'11','dec':'12'}
       a = d[0].strip()[:3].lower()
       d[0]=months[a]
       
       if len(d[1]) <2:
            d[1]='0'+d[1]
       date_format = [d[1],d[0],d[2]]
       return "/".join(date_format)
    #    if d[0].isnumeric():
    #          a = d[1].strip()[:3].lower()
    #          if len(d[0]) <2:
    #                 d[0]='0'+d[0]
    #          d[1]=months[a]
    #          return "/".join(d)
    #    else:

        

      
def b(text):
    txt = text.split()
    
    day = txt[1]
    for ch in ['st','th','nd','rd']:
        if ch in day:
            day = day.replace(ch,"")
    txt[1]=day
    return " ".join(txt)


def remove_signs(txt):
    for ch in ['…','...','--',',','–','+','-',':',';','★','☆','/','\'@','#','%','^','&','*','(',')','=','_',']','[','“','”','‘','’','—']:
        if ch in txt:
            txt = txt.replace(ch,"")
    return txt



def add_spaces(phrase,word):  #in some articles when search keyword is changed by tags in html - need to add spaces
    #first,last,word_with_spaces="","",""
    final=[]
    as_list= phrase.split()
    for w in as_list:
        if word in w and len(w)!=len(word):
            index_first = w.find(word)
            index_last = index_first +len(word)
            first = w[:index_first]
            last = w[index_last:]
            word_with_spaces = " "+word+" "
            final.append(first+word_with_spaces+ last)
        else:
            final.append(w)
    return " ".join(final)

--------------------------------------------------------------------------------------------------------------------
CNBC
--------------------------------------------------------------------------------------------------------------------

In [90]:
df_cnbc

,newspaper,title,date,abstract,link
0,CNBC,"This new, concentrated ETF lets investors bet ...",2023-03-21T13:46:08+0000,A new ETF hitting the market this week is aime...,https://www.cnbc.com/2023/03/21/this-new-conce...
1,CNBC,"Here are Monday's biggest analyst calls: UBS, ...",2023-03-20T10:09:29+0000,Here are Monday's biggest calls on Wall Street...,https://www.cnbc.com/2023/03/20/mondays-bigges...
2,CNBC,SVB listed remote work as a business risk befo...,2023-03-17T17:13:18+0000,Those following along with the collapse of Sil...,https://www.cnbc.com/2023/03/17/svb-listed-rem...
3,CNBC,"Bitcoin rallies above $26,000 as regulators ey...",2023-03-17T15:00:01+0000,CNBC Crypto World features the latest news and...,https://www.cnbc.com/video/2023/03/17/bitcoin-...
4,CNBC,Wall Street says Meta job cuts reiterate focus...,2023-03-15T15:00:29+0000,The latest round of job cuts at Meta Platforms...,https://www.cnbc.com/2023/03/15/wall-street-sa...
...,...,...,...,...,...
875,CNBC,Fortnite creator Epic Games buys the developer...,2021-03-03T05:07:25+0000,LONDON — Fortnite developer Epic Games has acq...,https://www.cnbc.com/2021/03/02/epic-games-buy...
876,CNBC,How a 10-second video clip sold for $6.6 million,2021-03-01T08:31:09+0000,"In October 2020, Miami-based art collector Pab...",https://www.cnbc.com/2021/03/01/how-a-10-secon...
877,CNBC,Roblox is chasing older users for games and vi...,2021-03-08T11:54:21+0000,Roblox is counting on adults to buy its stock ...,https://www.cnbc.com/2021/02/26/roblox-is-chas...
878,CNBC,Facebook's latest virtual reality headset is t...,2020-09-16T18:26:48+0000,Facebook on Wednesday announced the Oculus Que...,https://www.cnbc.com/2020/09/16/facebook-oculu...
879,CNBC,Amazon is developing three new sci-fi shows in...,2017-09-29T14:34:05+0000,"Earlier this month, Variety reported that Amaz...",https://www.cnbc.com/2017/09/29/amazon-making-...

In [91]:

df_cnbc['abstract']= df_cnbc.apply(lambda row :remove_signs(row['abstract']),axis=1)
df_cnbc['title']= df_cnbc.apply(lambda row :remove_signs(row['title']),axis=1)

df_cnbc

,newspaper,title,date,abstract,link
0,CNBC,This new concentrated ETF lets investors bet o...,2023-03-21T13:46:08+0000,A new ETF hitting the market this week is aime...,https://www.cnbc.com/2023/03/21/this-new-conce...
1,CNBC,Here are Monday's biggest analyst calls UBS Ne...,2023-03-20T10:09:29+0000,Here are Monday's biggest calls on Wall Street...,https://www.cnbc.com/2023/03/20/mondays-bigges...
2,CNBC,SVB listed remote work as a business risk befo...,2023-03-17T17:13:18+0000,Those following along with the collapse of Sil...,https://www.cnbc.com/2023/03/17/svb-listed-rem...
3,CNBC,Bitcoin rallies above $26000 as regulators eye...,2023-03-17T15:00:01+0000,CNBC Crypto World features the latest news and...,https://www.cnbc.com/video/2023/03/17/bitcoin-...
4,CNBC,Wall Street says Meta job cuts reiterate focus...,2023-03-15T15:00:29+0000,The latest round of job cuts at Meta Platforms...,https://www.cnbc.com/2023/03/15/wall-street-sa...
...,...,...,...,...,...
875,CNBC,Fortnite creator Epic Games buys the developer...,2021-03-03T05:07:25+0000,LONDON Fortnite developer Epic Games has acqu...,https://www.cnbc.com/2021/03/02/epic-games-buy...
876,CNBC,How a 10second video clip sold for $6.6 million,2021-03-01T08:31:09+0000,In October 2020 Miamibased art collector Pablo...,https://www.cnbc.com/2021/03/01/how-a-10-secon...
877,CNBC,Roblox is chasing older users for games and vi...,2021-03-08T11:54:21+0000,Roblox is counting on adults to buy its stock ...,https://www.cnbc.com/2021/02/26/roblox-is-chas...
878,CNBC,Facebook's latest virtual reality headset is t...,2020-09-16T18:26:48+0000,Facebook on Wednesday announced the Oculus Que...,https://www.cnbc.com/2020/09/16/facebook-oculu...
879,CNBC,Amazon is developing three new scifi shows in ...,2017-09-29T14:34:05+0000,Earlier this month Variety reported that Amazo...,https://www.cnbc.com/2017/09/29/amazon-making-...

In [92]:
df_cnbc=df_cnbc.replace(r'^\s*$', np.nan, regex=True)
df_cnbc = df_cnbc.dropna()
df_cnbc

,newspaper,title,date,abstract,link
0,CNBC,This new concentrated ETF lets investors bet o...,2023-03-21T13:46:08+0000,A new ETF hitting the market this week is aime...,https://www.cnbc.com/2023/03/21/this-new-conce...
1,CNBC,Here are Monday's biggest analyst calls UBS Ne...,2023-03-20T10:09:29+0000,Here are Monday's biggest calls on Wall Street...,https://www.cnbc.com/2023/03/20/mondays-bigges...
2,CNBC,SVB listed remote work as a business risk befo...,2023-03-17T17:13:18+0000,Those following along with the collapse of Sil...,https://www.cnbc.com/2023/03/17/svb-listed-rem...
3,CNBC,Bitcoin rallies above $26000 as regulators eye...,2023-03-17T15:00:01+0000,CNBC Crypto World features the latest news and...,https://www.cnbc.com/video/2023/03/17/bitcoin-...
4,CNBC,Wall Street says Meta job cuts reiterate focus...,2023-03-15T15:00:29+0000,The latest round of job cuts at Meta Platforms...,https://www.cnbc.com/2023/03/15/wall-street-sa...
...,...,...,...,...,...
875,CNBC,Fortnite creator Epic Games buys the developer...,2021-03-03T05:07:25+0000,LONDON Fortnite developer Epic Games has acqu...,https://www.cnbc.com/2021/03/02/epic-games-buy...
876,CNBC,How a 10second video clip sold for $6.6 million,2021-03-01T08:31:09+0000,In October 2020 Miamibased art collector Pablo...,https://www.cnbc.com/2021/03/01/how-a-10-secon...
877,CNBC,Roblox is chasing older users for games and vi...,2021-03-08T11:54:21+0000,Roblox is counting on adults to buy its stock ...,https://www.cnbc.com/2021/02/26/roblox-is-chas...
878,CNBC,Facebook's latest virtual reality headset is t...,2020-09-16T18:26:48+0000,Facebook on Wednesday announced the Oculus Que...,https://www.cnbc.com/2020/09/16/facebook-oculu...
879,CNBC,Amazon is developing three new scifi shows in ...,2017-09-29T14:34:05+0000,Earlier this month Variety reported that Amazo...,https://www.cnbc.com/2017/09/29/amazon-making-...

In [93]:
def substring(a):  
   a=a.split("T")
   return a[0]
df_cnbc['date']= df_cnbc.apply(lambda row :substring(row['date']),axis=1)
df_cnbc

,newspaper,title,date,abstract,link
0,CNBC,This new concentrated ETF lets investors bet o...,2023-03-21,A new ETF hitting the market this week is aime...,https://www.cnbc.com/2023/03/21/this-new-conce...
1,CNBC,Here are Monday's biggest analyst calls UBS Ne...,2023-03-20,Here are Monday's biggest calls on Wall Street...,https://www.cnbc.com/2023/03/20/mondays-bigges...
2,CNBC,SVB listed remote work as a business risk befo...,2023-03-17,Those following along with the collapse of Sil...,https://www.cnbc.com/2023/03/17/svb-listed-rem...
3,CNBC,Bitcoin rallies above $26000 as regulators eye...,2023-03-17,CNBC Crypto World features the latest news and...,https://www.cnbc.com/video/2023/03/17/bitcoin-...
4,CNBC,Wall Street says Meta job cuts reiterate focus...,2023-03-15,The latest round of job cuts at Meta Platforms...,https://www.cnbc.com/2023/03/15/wall-street-sa...
...,...,...,...,...,...
875,CNBC,Fortnite creator Epic Games buys the developer...,2021-03-03,LONDON Fortnite developer Epic Games has acqu...,https://www.cnbc.com/2021/03/02/epic-games-buy...
876,CNBC,How a 10second video clip sold for $6.6 million,2021-03-01,In October 2020 Miamibased art collector Pablo...,https://www.cnbc.com/2021/03/01/how-a-10-secon...
877,CNBC,Roblox is chasing older users for games and vi...,2021-03-08,Roblox is counting on adults to buy its stock ...,https://www.cnbc.com/2021/02/26/roblox-is-chas...
878,CNBC,Facebook's latest virtual reality headset is t...,2020-09-16,Facebook on Wednesday announced the Oculus Que...,https://www.cnbc.com/2020/09/16/facebook-oculu...
879,CNBC,Amazon is developing three new scifi shows in ...,2017-09-29,Earlier this month Variety reported that Amazo...,https://www.cnbc.com/2017/09/29/amazon-making-...

In [94]:
df_cnbc['date']=pd.to_datetime(df_cnbc.date, format='%Y-%m-%d')


filtered_df = df_cnbc[(df_cnbc['date'] >= '2021-01-01') & (df_cnbc['date'] < '2023-01-01') ]
unique_cnbc = filtered_df.drop_duplicates()

unique_cnbc.to_csv("cnbc_filtered.csv",encoding="utf-8-sig", sep=';',index=False)

--------------------------------------------------------------------------------------------------------------------
MAIL ONLINE
--------------------------------------------------------------------------------------------------------------------

In [95]:

df_mo['date'] = df_mo['date'].apply(substring_date)
df_mo.head()

,newspaper,title,date,abstract,link
0,Mail Online,virtual meanjin takes visitors on journey back...,March 21st 2023,what would you see if you entered a world-firs...,https://www.dailymail.co.uk/home/wires/aap/art...
1,Mail Online,"amazon confirms another 9,000 job cuts - addin...",March 20th 2023,"in the memo, ceo andy jassy said the second ph...",https://www.dailymail.co.uk/home/sciencetech/a...
2,Mail Online,"meta axes another 10,000 jobs in new round of ...",March 14th 2023,facebook owner meta announced a fresh wave of ...,https://www.dailymail.co.uk/home/wires/afp/art...
3,Mail Online,"meta to cut 10,000 jobs in second round of lay...",March 14th 2023,by katie paul and nivedita balumarch 14 (reute...,https://www.dailymail.co.uk/home/wires/reuters...
4,Mail Online,microsoft inks licensing deal with cloud gamin...,March 14th 2023,"by foo yun cheebrussels, march 14 (reuters) - ...",https://www.dailymail.co.uk/home/wires/reuters...

In [96]:
df_mo['abstract']=df_mo.apply(lambda row :remove_signs(row['abstract']),axis=1)
df_mo['title']=df_mo.apply(lambda row :remove_signs(row['title']),axis=1)

df_mo

,newspaper,title,date,abstract,link
0,Mail Online,virtual meanjin takes visitors on journey back...,March 21st 2023,what would you see if you entered a worldfirst...,https://www.dailymail.co.uk/home/wires/aap/art...
1,Mail Online,amazon confirms another 9000 job cuts adding ...,March 20th 2023,in the memo ceo andy jassy said the second pha...,https://www.dailymail.co.uk/home/sciencetech/a...
2,Mail Online,meta axes another 10000 jobs in new round of cuts,March 14th 2023,facebook owner meta announced a fresh wave of ...,https://www.dailymail.co.uk/home/wires/afp/art...
3,Mail Online,meta to cut 10000 jobs in second round of layoffs,March 14th 2023,by katie paul and nivedita balumarch 14 reuter...,https://www.dailymail.co.uk/home/wires/reuters...
4,Mail Online,microsoft inks licensing deal with cloud gamin...,March 14th 2023,by foo yun cheebrussels march 14 reuters micr...,https://www.dailymail.co.uk/home/wires/reuters...
...,...,...,...,...,...
669,Mail Online,selfdriving race car crashes straight into a w...,October 30th 2020,a roborace in the uk took a wrong turn when on...,https://www.dailymail.co.uk/home/sciencetech/a...
670,Mail Online,minecraft creators reveal the game has sold ov...,June 3rd 2016,minecraft creators revealed the game has now b...,https://www.dailymail.co.uk/home/sciencetech/a...
671,Mail Online,minecraft goes virtual! microsoft release vr v...,April 29th 2016,minecraft gear vr edition is a mobile virtual ...,https://www.dailymail.co.uk/home/sciencetech/a...
672,Mail Online,forget facebook world's first mobile vr social...,January 7th 2016,vtime is the work of liverpoolbased starship w...,https://www.dailymail.co.uk/home/sciencetech/a...
673,Mail Online,right or wrong? facebook monitors chat convers...,July 13th 2012,facebook's extensive but littlediscussed techn...,https://www.dailymail.co.uk/home/sciencetech/a...

In [97]:
df_mo=df_mo.replace(r'^\s*$', np.nan, regex=True)
df_mo

,newspaper,title,date,abstract,link
0,Mail Online,virtual meanjin takes visitors on journey back...,March 21st 2023,what would you see if you entered a worldfirst...,https://www.dailymail.co.uk/home/wires/aap/art...
1,Mail Online,amazon confirms another 9000 job cuts adding ...,March 20th 2023,in the memo ceo andy jassy said the second pha...,https://www.dailymail.co.uk/home/sciencetech/a...
2,Mail Online,meta axes another 10000 jobs in new round of cuts,March 14th 2023,facebook owner meta announced a fresh wave of ...,https://www.dailymail.co.uk/home/wires/afp/art...
3,Mail Online,meta to cut 10000 jobs in second round of layoffs,March 14th 2023,by katie paul and nivedita balumarch 14 reuter...,https://www.dailymail.co.uk/home/wires/reuters...
4,Mail Online,microsoft inks licensing deal with cloud gamin...,March 14th 2023,by foo yun cheebrussels march 14 reuters micr...,https://www.dailymail.co.uk/home/wires/reuters...
...,...,...,...,...,...
669,Mail Online,selfdriving race car crashes straight into a w...,October 30th 2020,a roborace in the uk took a wrong turn when on...,https://www.dailymail.co.uk/home/sciencetech/a...
670,Mail Online,minecraft creators reveal the game has sold ov...,June 3rd 2016,minecraft creators revealed the game has now b...,https://www.dailymail.co.uk/home/sciencetech/a...
671,Mail Online,minecraft goes virtual! microsoft release vr v...,April 29th 2016,minecraft gear vr edition is a mobile virtual ...,https://www.dailymail.co.uk/home/sciencetech/a...
672,Mail Online,forget facebook world's first mobile vr social...,January 7th 2016,vtime is the work of liverpoolbased starship w...,https://www.dailymail.co.uk/home/sciencetech/a...
673,Mail Online,right or wrong? facebook monitors chat convers...,July 13th 2012,facebook's extensive but littlediscussed techn...,https://www.dailymail.co.uk/home/sciencetech/a...

In [98]:

df_mo=df_mo.dropna()
df_mo

,newspaper,title,date,abstract,link
0,Mail Online,virtual meanjin takes visitors on journey back...,March 21st 2023,what would you see if you entered a worldfirst...,https://www.dailymail.co.uk/home/wires/aap/art...
1,Mail Online,amazon confirms another 9000 job cuts adding ...,March 20th 2023,in the memo ceo andy jassy said the second pha...,https://www.dailymail.co.uk/home/sciencetech/a...
2,Mail Online,meta axes another 10000 jobs in new round of cuts,March 14th 2023,facebook owner meta announced a fresh wave of ...,https://www.dailymail.co.uk/home/wires/afp/art...
3,Mail Online,meta to cut 10000 jobs in second round of layoffs,March 14th 2023,by katie paul and nivedita balumarch 14 reuter...,https://www.dailymail.co.uk/home/wires/reuters...
4,Mail Online,microsoft inks licensing deal with cloud gamin...,March 14th 2023,by foo yun cheebrussels march 14 reuters micr...,https://www.dailymail.co.uk/home/wires/reuters...
...,...,...,...,...,...
669,Mail Online,selfdriving race car crashes straight into a w...,October 30th 2020,a roborace in the uk took a wrong turn when on...,https://www.dailymail.co.uk/home/sciencetech/a...
670,Mail Online,minecraft creators reveal the game has sold ov...,June 3rd 2016,minecraft creators revealed the game has now b...,https://www.dailymail.co.uk/home/sciencetech/a...
671,Mail Online,minecraft goes virtual! microsoft release vr v...,April 29th 2016,minecraft gear vr edition is a mobile virtual ...,https://www.dailymail.co.uk/home/sciencetech/a...
672,Mail Online,forget facebook world's first mobile vr social...,January 7th 2016,vtime is the work of liverpoolbased starship w...,https://www.dailymail.co.uk/home/sciencetech/a...
673,Mail Online,right or wrong? facebook monitors chat convers...,July 13th 2012,facebook's extensive but littlediscussed techn...,https://www.dailymail.co.uk/home/sciencetech/a...

In [99]:


df_mo['date'] = df_mo['date'].apply(b)
df_mo.head(10)

,newspaper,title,date,abstract,link
0,Mail Online,virtual meanjin takes visitors on journey back...,March 21 2023,what would you see if you entered a worldfirst...,https://www.dailymail.co.uk/home/wires/aap/art...
1,Mail Online,amazon confirms another 9000 job cuts adding ...,March 20 2023,in the memo ceo andy jassy said the second pha...,https://www.dailymail.co.uk/home/sciencetech/a...
2,Mail Online,meta axes another 10000 jobs in new round of cuts,March 14 2023,facebook owner meta announced a fresh wave of ...,https://www.dailymail.co.uk/home/wires/afp/art...
3,Mail Online,meta to cut 10000 jobs in second round of layoffs,March 14 2023,by katie paul and nivedita balumarch 14 reuter...,https://www.dailymail.co.uk/home/wires/reuters...
4,Mail Online,microsoft inks licensing deal with cloud gamin...,March 14 2023,by foo yun cheebrussels march 14 reuters micr...,https://www.dailymail.co.uk/home/wires/reuters...
5,Mail Online,a 2nd wave of layoffs at meta 10000 jobs are cut,March 14 2023,facebook parent meta is slashing 10000 jobs ab...,https://www.dailymail.co.uk/home/wires/ap/arti...
6,Mail Online,microsoft signs licensing deal with cloud gami...,March 14 2023,brussels march 14 reuters microsoft on tuesd...,https://www.dailymail.co.uk/home/wires/reuters...
7,Mail Online,are they for real? south korean girl band offe...,March 14 2023,by hyunsu yimseoul march 14 reuters less than...,https://www.dailymail.co.uk/home/wires/reuters...
8,Mail Online,mark zuckerberg was 'personally' warned about ...,March 13 2023,the statements come from recently unsealed par...,https://www.dailymail.co.uk/home/sciencetech/a...
9,Mail Online,kpop giant hybe drops bid for sm entertainment...,March 12 2023,by hyunsu yim and jumin parkseoul march 12 reu...,https://www.dailymail.co.uk/home/wires/reuters...

In [100]:

df_mo['date'] = df_mo['date'].apply(month_converter)
df_mo.head(10)

,newspaper,title,date,abstract,link
0,Mail Online,virtual meanjin takes visitors on journey back...,21/03/2023,what would you see if you entered a worldfirst...,https://www.dailymail.co.uk/home/wires/aap/art...
1,Mail Online,amazon confirms another 9000 job cuts adding ...,20/03/2023,in the memo ceo andy jassy said the second pha...,https://www.dailymail.co.uk/home/sciencetech/a...
2,Mail Online,meta axes another 10000 jobs in new round of cuts,14/03/2023,facebook owner meta announced a fresh wave of ...,https://www.dailymail.co.uk/home/wires/afp/art...
3,Mail Online,meta to cut 10000 jobs in second round of layoffs,14/03/2023,by katie paul and nivedita balumarch 14 reuter...,https://www.dailymail.co.uk/home/wires/reuters...
4,Mail Online,microsoft inks licensing deal with cloud gamin...,14/03/2023,by foo yun cheebrussels march 14 reuters micr...,https://www.dailymail.co.uk/home/wires/reuters...
5,Mail Online,a 2nd wave of layoffs at meta 10000 jobs are cut,14/03/2023,facebook parent meta is slashing 10000 jobs ab...,https://www.dailymail.co.uk/home/wires/ap/arti...
6,Mail Online,microsoft signs licensing deal with cloud gami...,14/03/2023,brussels march 14 reuters microsoft on tuesd...,https://www.dailymail.co.uk/home/wires/reuters...
7,Mail Online,are they for real? south korean girl band offe...,14/03/2023,by hyunsu yimseoul march 14 reuters less than...,https://www.dailymail.co.uk/home/wires/reuters...
8,Mail Online,mark zuckerberg was 'personally' warned about ...,13/03/2023,the statements come from recently unsealed par...,https://www.dailymail.co.uk/home/sciencetech/a...
9,Mail Online,kpop giant hybe drops bid for sm entertainment...,12/03/2023,by hyunsu yim and jumin parkseoul march 12 reu...,https://www.dailymail.co.uk/home/wires/reuters...

In [101]:
def remove_from_url(link):
    return link.replace("/home","")

df_mo['link'] = df_mo['link'].apply(remove_from_url)
df_mo

,newspaper,title,date,abstract,link
0,Mail Online,virtual meanjin takes visitors on journey back...,21/03/2023,what would you see if you entered a worldfirst...,https://www.dailymail.co.uk/wires/aap/article-...
1,Mail Online,amazon confirms another 9000 job cuts adding ...,20/03/2023,in the memo ceo andy jassy said the second pha...,https://www.dailymail.co.uk/sciencetech/articl...
2,Mail Online,meta axes another 10000 jobs in new round of cuts,14/03/2023,facebook owner meta announced a fresh wave of ...,https://www.dailymail.co.uk/wires/afp/article-...
3,Mail Online,meta to cut 10000 jobs in second round of layoffs,14/03/2023,by katie paul and nivedita balumarch 14 reuter...,https://www.dailymail.co.uk/wires/reuters/arti...
4,Mail Online,microsoft inks licensing deal with cloud gamin...,14/03/2023,by foo yun cheebrussels march 14 reuters micr...,https://www.dailymail.co.uk/wires/reuters/arti...
...,...,...,...,...,...
669,Mail Online,selfdriving race car crashes straight into a w...,30/10/2020,a roborace in the uk took a wrong turn when on...,https://www.dailymail.co.uk/sciencetech/articl...
670,Mail Online,minecraft creators reveal the game has sold ov...,03/06/2016,minecraft creators revealed the game has now b...,https://www.dailymail.co.uk/sciencetech/articl...
671,Mail Online,minecraft goes virtual! microsoft release vr v...,29/04/2016,minecraft gear vr edition is a mobile virtual ...,https://www.dailymail.co.uk/sciencetech/articl...
672,Mail Online,forget facebook world's first mobile vr social...,07/01/2016,vtime is the work of liverpoolbased starship w...,https://www.dailymail.co.uk/sciencetech/articl...
673,Mail Online,right or wrong? facebook monitors chat convers...,13/07/2012,facebook's extensive but littlediscussed techn...,https://www.dailymail.co.uk/sciencetech/articl...

In [102]:
def clean_abstract(text):
    if(') -') in text:
        return text[text.find(') -')+3:]
    else:
        return text

df_mo['abstract'] = df_mo.apply(lambda row :clean_abstract(row['abstract']),axis=1)
df_mo

,newspaper,title,date,abstract,link
0,Mail Online,virtual meanjin takes visitors on journey back...,21/03/2023,what would you see if you entered a worldfirst...,https://www.dailymail.co.uk/wires/aap/article-...
1,Mail Online,amazon confirms another 9000 job cuts adding ...,20/03/2023,in the memo ceo andy jassy said the second pha...,https://www.dailymail.co.uk/sciencetech/articl...
2,Mail Online,meta axes another 10000 jobs in new round of cuts,14/03/2023,facebook owner meta announced a fresh wave of ...,https://www.dailymail.co.uk/wires/afp/article-...
3,Mail Online,meta to cut 10000 jobs in second round of layoffs,14/03/2023,by katie paul and nivedita balumarch 14 reuter...,https://www.dailymail.co.uk/wires/reuters/arti...
4,Mail Online,microsoft inks licensing deal with cloud gamin...,14/03/2023,by foo yun cheebrussels march 14 reuters micr...,https://www.dailymail.co.uk/wires/reuters/arti...
...,...,...,...,...,...
669,Mail Online,selfdriving race car crashes straight into a w...,30/10/2020,a roborace in the uk took a wrong turn when on...,https://www.dailymail.co.uk/sciencetech/articl...
670,Mail Online,minecraft creators reveal the game has sold ov...,03/06/2016,minecraft creators revealed the game has now b...,https://www.dailymail.co.uk/sciencetech/articl...
671,Mail Online,minecraft goes virtual! microsoft release vr v...,29/04/2016,minecraft gear vr edition is a mobile virtual ...,https://www.dailymail.co.uk/sciencetech/articl...
672,Mail Online,forget facebook world's first mobile vr social...,07/01/2016,vtime is the work of liverpoolbased starship w...,https://www.dailymail.co.uk/sciencetech/articl...
673,Mail Online,right or wrong? facebook monitors chat convers...,13/07/2012,facebook's extensive but littlediscussed techn...,https://www.dailymail.co.uk/sciencetech/articl...

In [103]:
df_mo['date']=pd.to_datetime(df_mo.date, format='%d/%m/%Y')


filtered_df = df_mo[(df_mo['date'] >= '2021-01-01') & (df_mo['date'] < '2023-01-01')]
unique_mo = filtered_df.drop_duplicates()

unique_mo.to_csv("mail_filtered.csv",encoding="utf-8-sig", sep=';',index=False)

--------------------------------------------------------------------------------------------------------------------
FINANCIAL TIMES
--------------------------------------------------------------------------------------------------------------------

In [158]:
df_ft.head(10)

,newspaper,title,date,abstract,link
0,Financial Times,"on your marks, headset, go: my surprising, sca...","February 24, 2023",...he also points out that vr and themetaverse...,https://www.ft.com/content/151b1d9b-4eb3-4016-...
1,Financial Times,letter: themetaverseis like every new technology,"February 22, 2023","...like every new technology, making themetave...",https://www.ft.com/content/6c7773d0-8bb6-4746-...
2,Financial Times,meta: virtual reality ambitions meet real-worl...,"March 15, 2023",...the avatars in meta’s version of themetaver...,https://www.ft.com/content/ac902303-00c5-4e66-...
3,Financial Times,metaversecreator neal stephenson on the future...,"February 24, 2023",...do we need a headset to experience themetav...,https://www.ft.com/content/0ecab009-6543-4386-...
4,Financial Times,what gucci and others learnt from themetaverse,"February 24, 2023",...the beanie’s journey frommetaverseto realit...,https://www.ft.com/content/d4c3d51f-4568-400e-...
5,Financial Times,"philosophy class: on your marks, headset, go: ...","March 12, 2023",...how could the existence of themetaversesupp...,https://www.ft.com/content/03c3d8b8-0575-4788-...
6,Financial Times,themetaverseexplained,"February 24, 2023",...what is themetaverse? tim bradshaw on the ...,https://www.ft.com/content/3045787e-9e03-4d37-...
7,Financial Times,whatever happened to themetaverse?,"February 16, 2023",...themetaversehas a couple of major problems....,https://www.ft.com/content/bddec314-3f4c-4296-...
8,Financial Times,ftav’s further reading,"March 17, 2023",...the hill) — wealthy executives make millio...,https://www.ft.com/content/d1eea520-68c4-4602-...
9,Financial Times,courses in themetaversestruggle to compete wit...,"March 12, 2023",...“we have to offer people a wow experience i...,https://www.ft.com/content/4ea0dccb-aad7-4bac-...

In [159]:
df_ft['date'] = df_ft.apply(lambda row :remove_signs(row['date']),axis=1)

In [160]:
df_ft['date'] = df_ft.apply(lambda row :month_converter(row['date']),axis=1)

In [161]:
df_ft['abstract'] = df_ft.apply(lambda row :add_spaces(row['abstract'],"metaverse"),axis=1)
df_ft['title'] = df_ft.apply(lambda row :add_spaces(row['title'],"metaverse"),axis=1)
df_ft

,newspaper,title,date,abstract,link
0,Financial Times,"on your marks, headset, go: my surprising, sca...",24/02/2023,...he also points out that vr and the metavers...,https://www.ft.com/content/151b1d9b-4eb3-4016-...
1,Financial Times,letter: the metaverse is like every new techno...,22/02/2023,"...like every new technology, making the metav...",https://www.ft.com/content/6c7773d0-8bb6-4746-...
2,Financial Times,meta: virtual reality ambitions meet real-worl...,15/03/2023,...the avatars in meta’s version of the metave...,https://www.ft.com/content/ac902303-00c5-4e66-...
3,Financial Times,metaverse creator neal stephenson on the futu...,24/02/2023,...do we need a headset to experience the meta...,https://www.ft.com/content/0ecab009-6543-4386-...
4,Financial Times,what gucci and others learnt from the metaverse,24/02/2023,...the beanie’s journey from metaverse to real...,https://www.ft.com/content/d4c3d51f-4568-400e-...
...,...,...,...,...,...
608,Financial Times,facebook after the whistleblower: can zuckerbe...,27/10/2021,...he pledged the company would build the “suc...,https://www.ft.com/content/ba03ac89-d055-460d-...
609,Financial Times,the untold tale of how facebook’s cryptocurren...,10/03/2022,...facebook is now busy with a new grand proje...,https://www.ft.com/content/a88fb591-72d5-4b6b-...
610,Financial Times,the ft crypto glossary,21/10/2021,... metaverse : a vision of the future interne...,https://www.ft.com/content/df9f5795-2aaf-4088-...
611,Financial Times,crypto investor vignesh sundaresan: ‘it’s the ...,04/06/2021,"...with his mother, he named it metakovan, whi...",https://www.ft.com/content/79f3452f-89c9-4c56-...
612,Financial Times,my wild ride into the crypto world,16/07/2021,...the metaverse idea is to enjoy a life that ...,https://www.ft.com/content/3dd0d341-aeb4-48fe-...

In [162]:
df_ft['abstract'] = df_ft.apply(lambda row :remove_signs(row['abstract']),axis=1)
df_ft['title'] = df_ft.apply(lambda row :remove_signs(row['title']),axis=1)

df_ft

,newspaper,title,date,abstract,link
0,Financial Times,on your marks headset go my surprising scary t...,24/02/2023,he also points out that vr and the metaverse i...,https://www.ft.com/content/151b1d9b-4eb3-4016-...
1,Financial Times,letter the metaverse is like every new technology,22/02/2023,like every new technology making the metaverse...,https://www.ft.com/content/6c7773d0-8bb6-4746-...
2,Financial Times,meta virtual reality ambitions meet realworld ...,15/03/2023,the avatars in metas version of the metaverse ...,https://www.ft.com/content/ac902303-00c5-4e66-...
3,Financial Times,metaverse creator neal stephenson on the futu...,24/02/2023,do we need a headset to experience the metaver...,https://www.ft.com/content/0ecab009-6543-4386-...
4,Financial Times,what gucci and others learnt from the metaverse,24/02/2023,the beanies journey from metaverse to reality ...,https://www.ft.com/content/d4c3d51f-4568-400e-...
...,...,...,...,...,...
608,Financial Times,facebook after the whistleblower can zuckerber...,27/10/2021,he pledged the company would build the success...,https://www.ft.com/content/ba03ac89-d055-460d-...
609,Financial Times,the untold tale of how facebooks cryptocurrenc...,10/03/2022,facebook is now busy with a new grand project ...,https://www.ft.com/content/a88fb591-72d5-4b6b-...
610,Financial Times,the ft crypto glossary,21/10/2021,metaverse a vision of the future internet. a...,https://www.ft.com/content/df9f5795-2aaf-4088-...
611,Financial Times,crypto investor vignesh sundaresan its the nft...,04/06/2021,with his mother he named it metakovan which ca...,https://www.ft.com/content/79f3452f-89c9-4c56-...
612,Financial Times,my wild ride into the crypto world,16/07/2021,the metaverse idea is to enjoy a life that is ...,https://www.ft.com/content/3dd0d341-aeb4-48fe-...

In [163]:
df_ft['date']=pd.to_datetime(df_ft.date, format='%d/%m/%Y')
#df_ft['date']=df_ft['date'].dt.strftime('%d/%m/%Y')


filtered_df = df_ft[(df_ft['date'] >= '2021-01-01') & (df_ft['date'] < '2023-01-01')]
unique_ft = filtered_df.drop_duplicates()

unique_ft.to_csv("financial_times_filtered.csv",encoding="utf-8-sig", sep=';',index=False)

--------------------------------------------------------------------------------------------------------------------
THE TIMES
--------------------------------------------------------------------------------------------------------------------

In [110]:

def remove_first(data):
    d = data.split()
    return " ".join(d[1:])




df_t['date'] = df_t.apply(lambda row :remove_first(row['date']),axis=1)
df_t.head(10)

,newspaper,title,date,abstract,link
0,The Times,paedophiles are abusing children in the metave...,February 22 2023,the police have recorded the first child abuse...,https://www.thetimes.co.uk/article/paedophiles...
1,The Times,i went on a house viewing in the metaverse — a...,February 15 2023,… anywhere in the world.”so would i buy a home...,https://www.thetimes.co.uk/article/i-went-on-a...
2,The Times,a virtual landgrab as buyers snap up property ...,January 23 2023,… did not see an issue with the business model...,https://www.thetimes.co.uk/article/a-virtual-l...
3,The Times,harsh reality crashes into the metaverse,January 7 2023,"… ces conference, said this year there would f...",https://www.thetimes.co.uk/article/harsh-reali...
4,The Times,eu throws gala party for ‘global gateway’ meta...,December 1 2022,the much-vauntedmetaverseis a virtual world of...,https://www.thetimes.co.uk/article/eu-throws-g...
5,The Times,metaverse is no substitute for real-world tech...,November 2 2022,… might be renowned for its young digital noma...,https://www.thetimes.co.uk/article/metaverse-i...
6,The Times,history tells us the metaverse could take off....,October 29 2022,"… founder has bet his company, his fortune and...",https://www.thetimes.co.uk/article/mark-zucker...
7,The Times,across the metaverse: pop industry goes virtual,October 23 2022,"… are investors.however, other music industry ...",https://www.thetimes.co.uk/article/across-the-...
8,The Times,legal tech course beamed from the metaverse,October 20 2022,… lawyers help clients to navigate novel legal...,https://www.thetimes.co.uk/article/legal-tech-...
9,The Times,clouds gather on the horizon for mark zuckerbe...,October 8 2022,"… at meta want to use it, leaks suggest. memos...",https://www.thetimes.co.uk/article/clouds-gath...

In [111]:
df_t['date'] = df_t.apply(lambda row :month_converter(row['date']),axis=1)

In [112]:
df_t['abstract'] = df_t.apply(lambda row :remove_signs(row['abstract']),axis=1)
df_t['title'] = df_t.apply(lambda row :remove_signs(row['title']),axis=1)

df_t

,newspaper,title,date,abstract,link
0,The Times,paedophiles are abusing children in the metave...,22/02/2023,the police have recorded the first child abuse...,https://www.thetimes.co.uk/article/paedophiles...
1,The Times,i went on a house viewing in the metaverse an...,15/02/2023,anywhere in the world.so would i buy a home i...,https://www.thetimes.co.uk/article/i-went-on-a...
2,The Times,a virtual landgrab as buyers snap up property ...,23/01/2023,did not see an issue with the business model....,https://www.thetimes.co.uk/article/a-virtual-l...
3,The Times,harsh reality crashes into the metaverse,07/01/2023,ces conference said this year there would fin...,https://www.thetimes.co.uk/article/harsh-reali...
4,The Times,eu throws gala party for global gateway metave...,01/12/2022,the muchvauntedmetaverseis a virtual world of ...,https://www.thetimes.co.uk/article/eu-throws-g...
...,...,...,...,...,...
305,The Times,well duh mark zuckerbergs trip to dc was clas...,15/04/2018,still waiting. but an unusually large proport...,https://www.thetimes.co.uk/article/well-duh-ma...
306,The Times,brave new world that risks alienating diehard ...,04/12/2010,and play it. its gone for ever. thats scary. ...,https://www.thetimes.co.uk/article/brave-new-w...
307,The Times,at least the chicken kebabs were real,25/10/2007,you know youre at a virtual worlds conference ...,https://www.thetimes.co.uk/article/at-least-th...
308,The Times,google to test rival to second life,24/09/2007,google is thought to be set to trial,https://www.thetimes.co.uk/article/google-to-t...
309,The Times,wimbledon fans get chance of a second life fac...,30/06/2007,possible to watch an entire match through the...,https://www.thetimes.co.uk/article/wimbledon-f...

In [113]:
df_t['abstract'] = df_t.apply(lambda row :add_spaces(row['abstract'],"metaverse"),axis=1)
df_t['title'] = df_t.apply(lambda row :add_spaces(row['title'],"metaverse"),axis=1)
df_t.head(20)

,newspaper,title,date,abstract,link
0,The Times,paedophiles are abusing children in the metav...,22/02/2023,the police have recorded the first child abuse...,https://www.thetimes.co.uk/article/paedophiles...
1,The Times,i went on a house viewing in the metaverse ...,15/02/2023,anywhere in the world.so would i buy a home i...,https://www.thetimes.co.uk/article/i-went-on-a...
2,The Times,a virtual landgrab as buyers snap up property ...,23/01/2023,did not see an issue with the business model....,https://www.thetimes.co.uk/article/a-virtual-l...
3,The Times,harsh reality crashes into the metaverse,07/01/2023,ces conference said this year there would fin...,https://www.thetimes.co.uk/article/harsh-reali...
4,The Times,eu throws gala party for global gateway metav...,01/12/2022,the muchvaunted metaverse is a virtual world o...,https://www.thetimes.co.uk/article/eu-throws-g...
5,The Times,metaverse is no substitute for realworld tec...,02/11/2022,might be renowned for its young digital nomad...,https://www.thetimes.co.uk/article/metaverse-i...
6,The Times,history tells us the metaverse could take of...,29/10/2022,founder has bet his company his fortune and h...,https://www.thetimes.co.uk/article/mark-zucker...
7,The Times,across the metaverse pop industry goes virtual,23/10/2022,are investors.however other music industry fi...,https://www.thetimes.co.uk/article/across-the-...
8,The Times,legal tech course beamed from the metaverse,20/10/2022,lawyers help clients to navigate novel legal ...,https://www.thetimes.co.uk/article/legal-tech-...
9,The Times,clouds gather on the horizon for mark zuckerbe...,08/10/2022,at meta want to use it leaks suggest. memos f...,https://www.thetimes.co.uk/article/clouds-gath...
10,The Times,millions visit nikeland as brands fashion a fu...,03/10/2022,nike has attracted tens of millions of visitor...,https://www.thetimes.co.uk/article/millions-vi...
11,The Times,mark zuckerberg gets lost in space on his risk...,24/09/2022,metaverse makes limitations of virtual world ...,https://www.thetimes.co.uk/article/mark-zucker...
12,The Times,how we can preserve the rule of law in the me...,22/09/2022,fear did not feel virtual.this kind of virtua...,https://www.thetimes.co.uk/article/how-we-can-...
13,The Times,invesco manager joins big players seeking fort...,29/08/2022,investors to back companies involved in produ...,https://www.thetimes.co.uk/article/invesco-man...
14,The Times,out of this world! mtv video music awards will...,02/08/2022,metaverse to create a digital museum.bieber p...,https://www.thetimes.co.uk/article/out-of-this...
15,The Times,my metaverse is better than yours mark zucke...,31/07/2022,of the real and the virtual world the present...,https://www.thetimes.co.uk/article/my-metavers...
16,The Times,tempest fighter jet inside the virtual cockpit...,17/07/2022,a fighter jet screams out of the sky and dance...,https://www.thetimes.co.uk/article/tempest-fig...
17,The Times,the metaverse by matthew ball review are yo...,11/07/2022,american children “play a single game roblox ...,https://www.thetimes.co.uk/article/the-metaver...
18,The Times,refugees open the door to the metaverse in b...,07/07/2022,embrace hybrid learning during the pandemic. ...,https://www.thetimes.co.uk/article/refugees-op...
19,The Times,a thriving metaverse needs to have all the b...,29/06/2022,loudly facebook when it rebranded itself as m...,https://www.thetimes.co.uk/article/a-thriving-...

In [114]:
df_t['date']=pd.to_datetime(df_t.date, format='%d/%m/%Y')
df_t

,newspaper,title,date,abstract,link
0,The Times,paedophiles are abusing children in the metav...,2023-02-22,the police have recorded the first child abuse...,https://www.thetimes.co.uk/article/paedophiles...
1,The Times,i went on a house viewing in the metaverse ...,2023-02-15,anywhere in the world.so would i buy a home i...,https://www.thetimes.co.uk/article/i-went-on-a...
2,The Times,a virtual landgrab as buyers snap up property ...,2023-01-23,did not see an issue with the business model....,https://www.thetimes.co.uk/article/a-virtual-l...
3,The Times,harsh reality crashes into the metaverse,2023-01-07,ces conference said this year there would fin...,https://www.thetimes.co.uk/article/harsh-reali...
4,The Times,eu throws gala party for global gateway metav...,2022-12-01,the muchvaunted metaverse is a virtual world o...,https://www.thetimes.co.uk/article/eu-throws-g...
...,...,...,...,...,...
305,The Times,well duh mark zuckerbergs trip to dc was clas...,2018-04-15,still waiting. but an unusually large proport...,https://www.thetimes.co.uk/article/well-duh-ma...
306,The Times,brave new world that risks alienating diehard ...,2010-12-04,and play it. its gone for ever. thats scary. ...,https://www.thetimes.co.uk/article/brave-new-w...
307,The Times,at least the chicken kebabs were real,2007-10-25,you know youre at a virtual worlds conference ...,https://www.thetimes.co.uk/article/at-least-th...
308,The Times,google to test rival to second life,2007-09-24,google is thought to be set to trial,https://www.thetimes.co.uk/article/google-to-t...
309,The Times,wimbledon fans get chance of a second life fac...,2007-06-30,possible to watch an entire match through the...,https://www.thetimes.co.uk/article/wimbledon-f...

In [115]:
filtered_df = df_t[(df_t['date'] >= '2021-01-01') & (df_t['date'] < '2023-01-01')]
unique_t = filtered_df.drop_duplicates()

unique_t.to_csv('the_times_filtered.csv',encoding="utf-8-sig", sep=';',index=False)

--------------------------------------------------------------------------------------------------------------------
FORBES
--------------------------------------------------------------------------------------------------------------------

In [116]:
df_forbes

,newspaper,title,date,abstract,link
0,Forbes,leading the way: some industries are already u...,"Mar 20, 2023",powered by advancements in semiconductor techn...,https://www.forbes.com/simple-data/search/more...
1,Forbes,the metaverse explained,"Mar 10, 2023","understand what the metaverse is, and what the...",https://www.forbes.com/simple-data/search/more...
2,Forbes,why clinique’s next move in the metaverse is a...,"Mar 20, 2023","the all-immersive, multi-sensory gamified expe...",https://www.forbes.com/simple-data/search/more...
3,Forbes,how regulation will apply to the metaverse,"Mar 1, 2023",how existing laws will apply in the metaverse,https://www.forbes.com/simple-data/search/more...
4,Forbes,metaverse trends 2023: don’t wait for its poké...,"Mar 7, 2023",now is the time for spirited dialogues and ear...,https://www.forbes.com/simple-data/search/more...
...,...,...,...,...,...
1012,Forbes,"lenovo's ""new it"" to empower businesses and a ...","Oct 24, 2022","in an exclusive interview for forbes, i spoke...",https://www.forbes.com/simple-data/search/more...
1013,Forbes,money20/20 u.s. highlights the rise of embedde...,"Nov 7, 2022",money20/20 us was back in full force this year...,https://www.forbes.com/simple-data/search/more...
1014,Forbes,what will emerge from the current economic rea...,"Aug 22, 2022",tough times like these often lead to the creat...,https://www.forbes.com/simple-data/search/more...
1015,Forbes,gucci vault goes phygital with physical twins ...,"Oct 21, 2022",the brand's web3 roadmap continues to unfold.,https://www.forbes.com/simple-data/search/more...
1016,Forbes,innovation showdown: crypto and meta vs. indus...,"Nov 22, 2022",as crypto and digital tech giants face reality...,https://www.forbes.com/simple-data/search/more...

In [117]:


df_forbes['date'] = df_forbes.apply(lambda row :remove_signs(row['date']),axis=1)
df_forbes

,newspaper,title,date,abstract,link
0,Forbes,leading the way: some industries are already u...,Mar 20 2023,powered by advancements in semiconductor techn...,https://www.forbes.com/simple-data/search/more...
1,Forbes,the metaverse explained,Mar 10 2023,"understand what the metaverse is, and what the...",https://www.forbes.com/simple-data/search/more...
2,Forbes,why clinique’s next move in the metaverse is a...,Mar 20 2023,"the all-immersive, multi-sensory gamified expe...",https://www.forbes.com/simple-data/search/more...
3,Forbes,how regulation will apply to the metaverse,Mar 1 2023,how existing laws will apply in the metaverse,https://www.forbes.com/simple-data/search/more...
4,Forbes,metaverse trends 2023: don’t wait for its poké...,Mar 7 2023,now is the time for spirited dialogues and ear...,https://www.forbes.com/simple-data/search/more...
...,...,...,...,...,...
1012,Forbes,"lenovo's ""new it"" to empower businesses and a ...",Oct 24 2022,"in an exclusive interview for forbes, i spoke...",https://www.forbes.com/simple-data/search/more...
1013,Forbes,money20/20 u.s. highlights the rise of embedde...,Nov 7 2022,money20/20 us was back in full force this year...,https://www.forbes.com/simple-data/search/more...
1014,Forbes,what will emerge from the current economic rea...,Aug 22 2022,tough times like these often lead to the creat...,https://www.forbes.com/simple-data/search/more...
1015,Forbes,gucci vault goes phygital with physical twins ...,Oct 21 2022,the brand's web3 roadmap continues to unfold.,https://www.forbes.com/simple-data/search/more...
1016,Forbes,innovation showdown: crypto and meta vs. indus...,Nov 22 2022,as crypto and digital tech giants face reality...,https://www.forbes.com/simple-data/search/more...

In [118]:
df_forbes['abstract'] = df_forbes.apply(lambda row :remove_signs(str(row['abstract'])),axis=1)
df_forbes['title'] = df_forbes.apply(lambda row :remove_signs(row['title']),axis=1)

df_forbes

,newspaper,title,date,abstract,link
0,Forbes,leading the way some industries are already us...,Mar 20 2023,powered by advancements in semiconductor techn...,https://www.forbes.com/simple-data/search/more...
1,Forbes,the metaverse explained,Mar 10 2023,understand what the metaverse is and what the ...,https://www.forbes.com/simple-data/search/more...
2,Forbes,why cliniques next move in the metaverse is a ...,Mar 20 2023,the allimmersive multisensory gamified experie...,https://www.forbes.com/simple-data/search/more...
3,Forbes,how regulation will apply to the metaverse,Mar 1 2023,how existing laws will apply in the metaverse,https://www.forbes.com/simple-data/search/more...
4,Forbes,metaverse trends 2023 dont wait for its pokémo...,Mar 7 2023,now is the time for spirited dialogues and ear...,https://www.forbes.com/simple-data/search/more...
...,...,...,...,...,...
1012,Forbes,"lenovo's ""new it"" to empower businesses and a ...",Oct 24 2022,in an exclusive interview for forbes i spoke ...,https://www.forbes.com/simple-data/search/more...
1013,Forbes,money2020 u.s. highlights the rise of embedded...,Nov 7 2022,money2020 us was back in full force this year ...,https://www.forbes.com/simple-data/search/more...
1014,Forbes,what will emerge from the current economic rea...,Aug 22 2022,tough times like these often lead to the creat...,https://www.forbes.com/simple-data/search/more...
1015,Forbes,gucci vault goes phygital with physical twins ...,Oct 21 2022,the brand's web3 roadmap continues to unfold.,https://www.forbes.com/simple-data/search/more...
1016,Forbes,innovation showdown crypto and meta vs. indust...,Nov 22 2022,as crypto and digital tech giants face reality...,https://www.forbes.com/simple-data/search/more...

In [119]:
df_forbes['date'] = df_forbes.apply(lambda row :month_converter(row['date']),axis=1)
df_forbes

,newspaper,title,date,abstract,link
0,Forbes,leading the way some industries are already us...,20/03/2023,powered by advancements in semiconductor techn...,https://www.forbes.com/simple-data/search/more...
1,Forbes,the metaverse explained,10/03/2023,understand what the metaverse is and what the ...,https://www.forbes.com/simple-data/search/more...
2,Forbes,why cliniques next move in the metaverse is a ...,20/03/2023,the allimmersive multisensory gamified experie...,https://www.forbes.com/simple-data/search/more...
3,Forbes,how regulation will apply to the metaverse,01/03/2023,how existing laws will apply in the metaverse,https://www.forbes.com/simple-data/search/more...
4,Forbes,metaverse trends 2023 dont wait for its pokémo...,07/03/2023,now is the time for spirited dialogues and ear...,https://www.forbes.com/simple-data/search/more...
...,...,...,...,...,...
1012,Forbes,"lenovo's ""new it"" to empower businesses and a ...",24/10/2022,in an exclusive interview for forbes i spoke ...,https://www.forbes.com/simple-data/search/more...
1013,Forbes,money2020 u.s. highlights the rise of embedded...,07/11/2022,money2020 us was back in full force this year ...,https://www.forbes.com/simple-data/search/more...
1014,Forbes,what will emerge from the current economic rea...,22/08/2022,tough times like these often lead to the creat...,https://www.forbes.com/simple-data/search/more...
1015,Forbes,gucci vault goes phygital with physical twins ...,21/10/2022,the brand's web3 roadmap continues to unfold.,https://www.forbes.com/simple-data/search/more...
1016,Forbes,innovation showdown crypto and meta vs. indust...,22/11/2022,as crypto and digital tech giants face reality...,https://www.forbes.com/simple-data/search/more...

In [120]:
df_forbes['date']=pd.to_datetime(df_forbes.date, format='%d/%m/%Y')

filtered_df = df_forbes[(df_forbes['date'] >= '2021-01-01') & (df_forbes['date'] < '2023-01-01')]
unique_forbes = filtered_df.drop_duplicates()
unique_forbes
unique_forbes.to_csv('forbes_filtered.csv',encoding="utf-8-sig", sep=';',index=False)

-----------------------------------------------------------------------------------------------------------
BLOOMBERG 
-----------------------------------------------------------------------------------------------------------

In [122]:
df_bloomberg

,newspaper,title,date,abstract,link
0,Bloomberg,"Apple Cost-Cutting Efforts: No Layoffs, But Le...","March 19, 2023",Apple is pulling every lever it can to cut cos...,https://www.bloomberg.com/news/newsletters/202...
1,Bloomberg,Game Studio Double Fine Films Itself for ‘Psyc...,"March 17, 2023",Hi everyone. Today I’m taking you behind the s...,https://www.bloomberg.com/news/newsletters/202...
2,Bloomberg,Meta Layoffs Reveal a Deeper Truth: Tech Excep...,"March 15, 2023",Silicon Valley for too long equated rapid head...,https://www.bloomberg.com/opinion/articles/202...
3,Bloomberg,"Nuclear Submarine AUKUS Deal: US, UK and Austr...","March 14, 2023",A historic defense accord will allow the US an...,https://www.bloomberg.com/opinion/articles/202...
4,Bloomberg,"Meta to Cut 10,000 Jobs, Slash 5,000 More Vaca...","March 14, 2023",Meta Platforms Inc. plans to lay off around 10...,https://www.bloomberg.com/news/articles/2023-0...
...,...,...,...,...,...
1195,Bloomberg,Bezos’s Wealth Falls $13.5 Billion as Amazon E...,"July 30, 2021",Amazon.com Inc.’s weaker-than-expected second-...,https://www.bloomberg.com/news/articles/2021-0...
1196,Bloomberg,Mark Zuckerberg Explains Metaverse Vision to F...,"July 28, 2021","The social media giant wants you to live, work...",https://www.bloomberg.com/news/articles/2021-0...
1197,Bloomberg,Facebook Says Apple Ad-Tracking ‘Headwinds’ Wi...,"July 28, 2021",Facebook Inc. reported higher second-quarter s...,https://www.bloomberg.com/news/articles/2021-0...
1198,Bloomberg,Delta Variant Is Spoiling New York’s Wild Summer,"July 23, 2021",London is a cautionary tale about what could c...,https://www.bloomberg.com/opinion/articles/202...
1199,Bloomberg,"Pace Gallery Is Ramping Up Digital Art, Even a...","July 2, 2021","Pace, which has locations around the globe, is...",https://www.bloomberg.com/news/articles/2021-0...

In [123]:


df_bloomberg['date'] = df_bloomberg.apply(lambda row :remove_signs(row['date']),axis=1)
df_bloomberg

,newspaper,title,date,abstract,link
0,Bloomberg,"Apple Cost-Cutting Efforts: No Layoffs, But Le...",March 19 2023,Apple is pulling every lever it can to cut cos...,https://www.bloomberg.com/news/newsletters/202...
1,Bloomberg,Game Studio Double Fine Films Itself for ‘Psyc...,March 17 2023,Hi everyone. Today I’m taking you behind the s...,https://www.bloomberg.com/news/newsletters/202...
2,Bloomberg,Meta Layoffs Reveal a Deeper Truth: Tech Excep...,March 15 2023,Silicon Valley for too long equated rapid head...,https://www.bloomberg.com/opinion/articles/202...
3,Bloomberg,"Nuclear Submarine AUKUS Deal: US, UK and Austr...",March 14 2023,A historic defense accord will allow the US an...,https://www.bloomberg.com/opinion/articles/202...
4,Bloomberg,"Meta to Cut 10,000 Jobs, Slash 5,000 More Vaca...",March 14 2023,Meta Platforms Inc. plans to lay off around 10...,https://www.bloomberg.com/news/articles/2023-0...
...,...,...,...,...,...
1195,Bloomberg,Bezos’s Wealth Falls $13.5 Billion as Amazon E...,July 30 2021,Amazon.com Inc.’s weaker-than-expected second-...,https://www.bloomberg.com/news/articles/2021-0...
1196,Bloomberg,Mark Zuckerberg Explains Metaverse Vision to F...,July 28 2021,"The social media giant wants you to live, work...",https://www.bloomberg.com/news/articles/2021-0...
1197,Bloomberg,Facebook Says Apple Ad-Tracking ‘Headwinds’ Wi...,July 28 2021,Facebook Inc. reported higher second-quarter s...,https://www.bloomberg.com/news/articles/2021-0...
1198,Bloomberg,Delta Variant Is Spoiling New York’s Wild Summer,July 23 2021,London is a cautionary tale about what could c...,https://www.bloomberg.com/opinion/articles/202...
1199,Bloomberg,"Pace Gallery Is Ramping Up Digital Art, Even a...",July 2 2021,"Pace, which has locations around the globe, is...",https://www.bloomberg.com/news/articles/2021-0...

In [124]:
df_bloomberg['date'] = df_bloomberg.apply(lambda row :month_converter(row['date']),axis=1)
df_bloomberg

,newspaper,title,date,abstract,link
0,Bloomberg,"Apple Cost-Cutting Efforts: No Layoffs, But Le...",19/03/2023,Apple is pulling every lever it can to cut cos...,https://www.bloomberg.com/news/newsletters/202...
1,Bloomberg,Game Studio Double Fine Films Itself for ‘Psyc...,17/03/2023,Hi everyone. Today I’m taking you behind the s...,https://www.bloomberg.com/news/newsletters/202...
2,Bloomberg,Meta Layoffs Reveal a Deeper Truth: Tech Excep...,15/03/2023,Silicon Valley for too long equated rapid head...,https://www.bloomberg.com/opinion/articles/202...
3,Bloomberg,"Nuclear Submarine AUKUS Deal: US, UK and Austr...",14/03/2023,A historic defense accord will allow the US an...,https://www.bloomberg.com/opinion/articles/202...
4,Bloomberg,"Meta to Cut 10,000 Jobs, Slash 5,000 More Vaca...",14/03/2023,Meta Platforms Inc. plans to lay off around 10...,https://www.bloomberg.com/news/articles/2023-0...
...,...,...,...,...,...
1195,Bloomberg,Bezos’s Wealth Falls $13.5 Billion as Amazon E...,30/07/2021,Amazon.com Inc.’s weaker-than-expected second-...,https://www.bloomberg.com/news/articles/2021-0...
1196,Bloomberg,Mark Zuckerberg Explains Metaverse Vision to F...,28/07/2021,"The social media giant wants you to live, work...",https://www.bloomberg.com/news/articles/2021-0...
1197,Bloomberg,Facebook Says Apple Ad-Tracking ‘Headwinds’ Wi...,28/07/2021,Facebook Inc. reported higher second-quarter s...,https://www.bloomberg.com/news/articles/2021-0...
1198,Bloomberg,Delta Variant Is Spoiling New York’s Wild Summer,23/07/2021,London is a cautionary tale about what could c...,https://www.bloomberg.com/opinion/articles/202...
1199,Bloomberg,"Pace Gallery Is Ramping Up Digital Art, Even a...",02/07/2021,"Pace, which has locations around the globe, is...",https://www.bloomberg.com/news/articles/2021-0...

In [125]:
df_bloomberg=df_bloomberg.replace(r'^\s*$', np.nan, regex=True)
df_bloomberg=df_bloomberg.dropna()
df_bloomberg

,newspaper,title,date,abstract,link
0,Bloomberg,"Apple Cost-Cutting Efforts: No Layoffs, But Le...",19/03/2023,Apple is pulling every lever it can to cut cos...,https://www.bloomberg.com/news/newsletters/202...
1,Bloomberg,Game Studio Double Fine Films Itself for ‘Psyc...,17/03/2023,Hi everyone. Today I’m taking you behind the s...,https://www.bloomberg.com/news/newsletters/202...
2,Bloomberg,Meta Layoffs Reveal a Deeper Truth: Tech Excep...,15/03/2023,Silicon Valley for too long equated rapid head...,https://www.bloomberg.com/opinion/articles/202...
3,Bloomberg,"Nuclear Submarine AUKUS Deal: US, UK and Austr...",14/03/2023,A historic defense accord will allow the US an...,https://www.bloomberg.com/opinion/articles/202...
4,Bloomberg,"Meta to Cut 10,000 Jobs, Slash 5,000 More Vaca...",14/03/2023,Meta Platforms Inc. plans to lay off around 10...,https://www.bloomberg.com/news/articles/2023-0...
...,...,...,...,...,...
1195,Bloomberg,Bezos’s Wealth Falls $13.5 Billion as Amazon E...,30/07/2021,Amazon.com Inc.’s weaker-than-expected second-...,https://www.bloomberg.com/news/articles/2021-0...
1196,Bloomberg,Mark Zuckerberg Explains Metaverse Vision to F...,28/07/2021,"The social media giant wants you to live, work...",https://www.bloomberg.com/news/articles/2021-0...
1197,Bloomberg,Facebook Says Apple Ad-Tracking ‘Headwinds’ Wi...,28/07/2021,Facebook Inc. reported higher second-quarter s...,https://www.bloomberg.com/news/articles/2021-0...
1198,Bloomberg,Delta Variant Is Spoiling New York’s Wild Summer,23/07/2021,London is a cautionary tale about what could c...,https://www.bloomberg.com/opinion/articles/202...
1199,Bloomberg,"Pace Gallery Is Ramping Up Digital Art, Even a...",02/07/2021,"Pace, which has locations around the globe, is...",https://www.bloomberg.com/news/articles/2021-0...

In [126]:
df_bloomberg['abstract'] = df_bloomberg.apply(lambda row :remove_signs(str(row['abstract'])),axis=1)
df_bloomberg['title'] = df_bloomberg.apply(lambda row :remove_signs(row['title']),axis=1)

df_bloomberg

,newspaper,title,date,abstract,link
0,Bloomberg,Apple CostCutting Efforts No Layoffs But Less ...,19/03/2023,Apple is pulling every lever it can to cut cos...,https://www.bloomberg.com/news/newsletters/202...
1,Bloomberg,Game Studio Double Fine Films Itself for Psych...,17/03/2023,Hi everyone. Today Im taking you behind the sc...,https://www.bloomberg.com/news/newsletters/202...
2,Bloomberg,Meta Layoffs Reveal a Deeper Truth Tech Except...,15/03/2023,Silicon Valley for too long equated rapid head...,https://www.bloomberg.com/opinion/articles/202...
3,Bloomberg,Nuclear Submarine AUKUS Deal US UK and Austral...,14/03/2023,A historic defense accord will allow the US an...,https://www.bloomberg.com/opinion/articles/202...
4,Bloomberg,Meta to Cut 10000 Jobs Slash 5000 More Vacant ...,14/03/2023,Meta Platforms Inc. plans to lay off around 10...,https://www.bloomberg.com/news/articles/2023-0...
...,...,...,...,...,...
1195,Bloomberg,Bezoss Wealth Falls $13.5 Billion as Amazon Ea...,30/07/2021,Amazon.com Inc.s weakerthanexpected secondquar...,https://www.bloomberg.com/news/articles/2021-0...
1196,Bloomberg,Mark Zuckerberg Explains Metaverse Vision to F...,28/07/2021,The social media giant wants you to live work ...,https://www.bloomberg.com/news/articles/2021-0...
1197,Bloomberg,Facebook Says Apple AdTracking Headwinds Will ...,28/07/2021,Facebook Inc. reported higher secondquarter sa...,https://www.bloomberg.com/news/articles/2021-0...
1198,Bloomberg,Delta Variant Is Spoiling New Yorks Wild Summer,23/07/2021,London is a cautionary tale about what could c...,https://www.bloomberg.com/opinion/articles/202...
1199,Bloomberg,Pace Gallery Is Ramping Up Digital Art Even as...,02/07/2021,Pace which has locations around the globe is b...,https://www.bloomberg.com/news/articles/2021-0...

In [127]:
df_bloomberg['date']=pd.to_datetime(df_bloomberg.date, format='%d/%m/%Y')

filtered_df = df_bloomberg[(df_bloomberg['date'] >= '2021-01-01') & (df_bloomberg['date'] < '2023-01-01')]
unique_bloom = filtered_df.drop_duplicates()

unique_bloom.to_csv('bloomberg_filtered.csv',encoding="utf-8-sig", sep=';',index=False)

concatenate csvs

In [165]:

all_filenames = ['mail_filtered.csv','forbes_filtered.csv','bloomberg_filtered.csv','financial_times_filtered.csv','the_times_filtered.csv','cnbc_filtered.csv']

df_all = pd.DataFrame()
 
# append the CSV files
for file in all_filenames:
    df = pd.read_csv(file,  sep=';', encoding='utf-8-sig')
    df_all = df_all.append(df, ignore_index=True)
 
df_all.to_csv( "news.csv",  sep=';', index=False, encoding='utf-8-sig')